### ISSUE TITLE
Allow evaluation of Rego based policies

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-evaluator#14]
Rego policies can be built into WebAssembly modules that can then be evaluated. We have proved this to be possible using [this POC](https://github.com/flavio/burrego)

The goal of this issues is to integrate the code of the POC into this crate.

# Admission criteria

* Simple OPA policy can be loaded and evaluated by kwctl and policy-server
* Simple Gatekeeper policy can be loaded and evaluated by kwctl and policy-server

# Linked cards

* [x] https://github.com/kubewarden/policy-evaluator/issues/15
* [x] https://github.com/kubewarden/kwctl/issues/55
* [x] https://github.com/kubewarden/policy-server/issues/76
* [x] https://github.com/kubewarden/policy-evaluator/issues/16

**Comment by flavio** [comment]
I think this can be closed right now, at least for Opa policies.

We will create new cards to handle Gatekeeper ones
